import { expect } from 'chai';
import { Collection, Model } from '../src';

// Setup
// ----------------------------------------------------------------------------

const collection: Collection.Schedule = Collection.Schedule.hydrate([
    {
        id: 672,
        title: 'Billy Thorpe vs Jason Klatt',
        description: '2016 USBTC 9-ball',
        duration: '4643',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://youtube.com/embed/vscAWV7V0RI',
        is_live: null,
        air_at: '',
        created_at: '2017-01-23 21:49:59',
    },
    {
        id: 422,
        title: 'Thorsten Hohmann vs Carlo Biado',
        description: '2013 8-ball',
        duration: '7321',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://youtube.com/embed/zO_bymWB1IQ',
        is_live: null,
        air_at: '',
        created_at: '2016-09-13 19:12:14',
    },
    {
        id: 3508,
        title: 'Cup Group  vs Solihull',
        description: ' 8-ball',
        duration: '14146',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/Vuuygnz-BnA',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 09:11:55',
    },
    {
        id: 12972,
        title: 'James Aranas vs Naoyuki',
        description: '2019 8-ball',
        duration: '4033',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/sw1qEnZwI2A',
        is_live: null,
        air_at: '',
        created_at: '2019-10-27 00:01:13',
    },
    {
        id: 9779,
        title: 'Josh Filler vs Fan Yang',
        description: '2019 10-ball',
        duration: '4281',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/n62vItEZHdk',
        is_live: null,
        air_at: '',
        created_at: '2019-07-28 00:01:29',
    },
    {
        id: 10130,
        title: 'Ipa Tour Coventry vs Friday',
        description: ' 8-ball',
        duration: '4280',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/Gsoz3wilnFY',
        is_live: null,
        air_at: '',
        created_at: '2019-08-04 00:02:11',
    },
    {
        id: 17407,
        title: 'Jeffrey Luna vs Dennis Orcollo',
        description: '2019 10-ball',
        duration: '8808',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/k0ECNqxJRU8',
        is_live: null,
        air_at: '',
        created_at: '2020-02-23 00:01:12',
    },
    {
        id: 9780,
        title: 'Open Niels Feijen vs Mieszko Fortunski',
        description: '2019 8-ball',
        duration: '7169',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/aq3vESOTMs8',
        is_live: null,
        air_at: '',
        created_at: '2019-07-28 00:01:29',
    },
    {
        id: 3392,
        title: ' Gary Lutman vs Bill Thompson',
        description: '2018 8-ball',
        duration: '4835',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/mt0SK71qkg8',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 09:11:55',
    },
    {
        id: 1064,
        title: 'Shane Van Boening vs Lee Van Corteza',
        description: '2017 US Open 8-ball',
        duration: '5053',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://youtube.com/embed/L1rq68Fx3_Y',
        is_live: null,
        air_at: '',
        created_at: '2017-11-07 22:50:53',
    },
    {
        id: 3585,
        title: 'Chumreon Sutcharitakul vs George ',
        description: ' 8-ball',
        duration: '3458',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/slrWrGNaxKU',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 09:11:55',
    },
    {
        id: 111,
        title: 'Shane Van Boening vs Ko Pin-Yi',
        description: '2014 10-ball',
        duration: '1629',
        video_meta: '{ "game_type": "10-ball" }',
        embed_url: 'https://www.youtube.com/embed/rPCFD2bOpuA',
        is_live: null,
        air_at: '',
        created_at: '2016-06-01 04:40:19',
    },
    {
        id: 5505,
        title: 'Max Eberle vs Chip Compton',
        description: '2018 10-ball',
        duration: '6029',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/WdTKWt6FsEI',
        is_live: null,
        air_at: '',
        created_at: '2019-03-17 00:01:14',
    },
    {
        id: 1073,
        title: 'Roberto Gomez vs Warren Kiamco',
        description: '2017 US Open 10-ball',
        duration: '6188',
        video_meta: '{ "game_type": "10-ball" }',
        embed_url: 'https://youtube.com/embed/4BBcWsi6c6M',
        is_live: null,
        air_at: '',
        created_at: '2017-11-07 22:53:30',
    },
    {
        id: 648,
        title: 'John Schmidt vs Santos Sambajon',
        description: '2016 1-pocket',
        duration: '12471',
        video_meta: '{ "game_type": "1-pocket" }',
        embed_url: 'https://youtube.com/embed/fYpdt8fci2c',
        is_live: null,
        air_at: '',
        created_at: '2017-01-23 21:44:31',
    },
    {
        id: 290,
        title: 'Efren Reyes vs Aaron Moore',
        description: '2016 1 Pocket',
        duration: '2324',
        video_meta: '{ "game_type": "1-pocket" }',
        embed_url: 'https://www.youtube.com/embed/eyJ5TiXuYj0',
        is_live: null,
        air_at: '',
        created_at: '2016-07-27 14:58:06',
    },
    {
        id: 19318,
        title: 'Drew Hughes vs Dave Mcnamara',
        description: ' 8-ball',
        duration: '4612',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/d-sNio0dB6A',
        is_live: null,
        air_at: '',
        created_at: '2020-04-12 00:01:12',
    },
    {
        id: 4386,
        title: 'Ernesto Dominguez vs Alex Olinger',
        description: '2018 8-ball',
        duration: '5681',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/z5iQlPlBDNc',
        is_live: null,
        air_at: '',
        created_at: '2019-02-10 00:01:17',
    },
    {
        id: 22,
        title: 'Mike Sigel vs Efren Reyes',
        description: '2005 8-Ball IPT King of the Hill ',
        duration: '9157',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://www.youtube.com/embed/U_a2zMFGMQE',
        is_live: null,
        air_at: '',
        created_at: '',
    },
    {
        id: 3488,
        title: 'Premier League  vs Week ',
        description: '2018 8-ball',
        duration: '13101',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/-7UgGjgNzro',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 09:11:55',
    },
    {
        id: 1040,
        title: 'Lucas vs Ward',
        description: '2017 Blackball',
        duration: '6005',
        video_meta: '{ "game_type": "blackball" }',
        embed_url: 'https://youtube.com/embed/kzwkVgZyfJs',
        is_live: null,
        air_at: '',
        created_at: '2017-09-28 05:35:19',
    },
    {
        id: 16,
        title: 'Rick Blacker vs Ozzy Reynolds',
        description: '2016 BCAPL Wisconsin State Championships',
        duration: '3840',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://www.youtube.com/embed/qtuGYgmiMJ4',
        is_live: null,
        air_at: '',
        created_at: '',
    },
    {
        id: 16083,
        title: 'Limit Van Boening vs Warren Kiamco',
        description: '2019 8-ball',
        duration: '11593',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/ZWnb36LEvwU',
        is_live: null,
        air_at: '',
        created_at: '2020-01-19 00:01:12',
    },
    {
        id: 1036,
        title: 'Oliver vs Chambers',
        description: '2017 Blackball',
        duration: '4743',
        video_meta: '{ "game_type": "blackball" }',
        embed_url: 'https://youtube.com/embed/6KWRal9XPjE',
        is_live: null,
        air_at: '',
        created_at: '2017-09-28 05:34:48',
    },
    {
        id: 1037,
        title: 'Ross vs White',
        description: '2017 Blackball',
        duration: '3943',
        video_meta: '{ "game_type": "blackball" }',
        embed_url: 'https://youtube.com/embed/AtjQG_fpyII',
        is_live: null,
        air_at: '',
        created_at: '2017-09-28 05:34:57',
    },
    {
        id: 23799,
        title: 'Skyler Woodward vs Max Eberle',
        description: '2019 8-ball',
        duration: '3930',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/MDtQo3MqvNE',
        is_live: null,
        air_at: '',
        created_at: '2020-09-20 00:00:45',
    },
    {
        id: 1055,
        title: 'Fedor Gorst vs Corey Deuel',
        description: '2017 9-ball',
        duration: '1741',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://youtube.com/embed/aAQQjpcgx8c',
        is_live: null,
        air_at: '',
        created_at: '2017-09-28 05:41:23',
    },
    {
        id: 18422,
        title: 'James Aranas vs Junglin Chang',
        description: '2020 8-ball',
        duration: '5841',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/R0MCnBkRX3g',
        is_live: null,
        air_at: '',
        created_at: '2020-03-22 00:01:17',
    },
    {
        id: 16888,
        title: 'Luck Thorsten Hohmann vs Corey Deuel',
        description: '2019 10-ball',
        duration: '6964',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/buNVnkwd8wE',
        is_live: null,
        air_at: '',
        created_at: '2020-02-09 00:01:18',
    },
    {
        id: 10384,
        title: 'Ipa Tour Coventry vs Saturday',
        description: ' 8-ball',
        duration: '8361',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/ONcuNaeTifQ',
        is_live: null,
        air_at: '',
        created_at: '2019-08-11 00:01:30',
    },
    {
        id: 214,
        title: 'K. Yukawa vs Allison Fisher',
        description: '2015 9-ball',
        duration: '5155',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://www.youtube.com/embed/co1kc_gBxy8',
        is_live: null,
        air_at: '',
        created_at: '2016-07-13 04:35:17',
    },
    {
        id: 3492,
        title: 'Champions Cup  vs s and ',
        description: '2018 8-ball',
        duration: '13256',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/t78-3E7sYa8',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 09:11:55',
    },
    {
        id: 430,
        title: 'Shane Van Boening vs Ronnie Alcano',
        description: '2012 10-ball',
        duration: '6743',
        video_meta: '{ "game_type": "10-ball" }',
        embed_url: 'https://youtube.com/embed/bDHFAHv4dZs',
        is_live: null,
        air_at: '',
        created_at: '2016-09-13 19:15:53',
    },
    {
        id: 25883,
        title: 'Fortunski Vs Giallourakis vs Villafuerte Vs Dellino',
        description: ' 8-ball',
        duration: '5708',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/TBPY9NcqqMY',
        is_live: null,
        air_at: '',
        created_at: '2020-12-13 00:00:50',
    },
    {
        id: 9781,
        title: 'Open Mieszko Fortunski vs Skyler Woodward',
        description: '2019 8-ball',
        duration: '3171',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/jMFDQAm9_w0',
        is_live: null,
        air_at: '',
        created_at: '2019-07-28 00:01:29',
    },
    {
        id: 32,
        title: 'Alex Higgins vs Jimmy White',
        description: '1982 Snooker',
        duration: '1675',
        video_meta: '{ "game_type": "snooker" }',
        embed_url: 'https://www.youtube.com/embed/y-yCyRPEBxM',
        is_live: null,
        air_at: '',
        created_at: '',
    },
    {
        id: 28007,
        title: 'Filler vs Ouschan Vs Styer',
        description: ' 8-ball',
        duration: '5835',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/6qpzYSZcvRw',
        is_live: null,
        air_at: '',
        created_at: '2021-03-07 00:00:34',
    },
    {
        id: 486,
        title: 'Mika Immonen vs Thorsten Hohmann',
        description: '2016 Straight Pool',
        duration: '7191',
        video_meta: '{ "game_type": "straight-pool" }',
        embed_url: 'https://youtube.com/embed/hB76NIW_VFY',
        is_live: null,
        air_at: '',
        created_at: '2016-10-27 18:38:51',
    },
    {
        id: 1171,
        title: 'Vinnie Calabrese vs Skyler Woodward',
        description: '2017 10-ball',
        duration: '2900',
        video_meta: '{ "game_type": "10-ball" }',
        embed_url: 'https://youtube.com/embed/wn-wJHw6ezc',
        is_live: null,
        air_at: '',
        created_at: '2018-08-20 14:52:33',
    },
    {
        id: 40,
        title: 'Mika Immonen vs Brandon Shuff',
        description: '2012 straight pool championship',
        duration: '6589',
        video_meta: '{ "game_type": "straight-pool" }',
        embed_url: 'https://www.youtube.com/embed/zZJN1G0-n2U',
        is_live: null,
        air_at: '',
        created_at: '',
    },
    {
        id: 1052,
        title: 'Fedor Gorst vs Shane Van Boening',
        description: '2017 9-ball',
        duration: '2673',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://youtube.com/embed/OTaiZtsUdnQ',
        is_live: null,
        air_at: '',
        created_at: '2017-09-28 05:40:37',
    },
    {
        id: 511,
        title: 'Moreno & Brown vs Stuckart & Kelly',
        description: '2016 8-ball',
        duration: '3531',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://youtube.com/embed/HL0oYc0xZOo',
        is_live: null,
        air_at: '',
        created_at: '2016-11-07 17:33:35',
    },
    {
        id: 448,
        title: 'Michael Wortmann vs Luca Srensen',
        description: '2016 10 Ball',
        duration: '1787',
        video_meta: '{ "game_type": "10-ball" }',
        embed_url: 'https://youtube.com/embed/0JvXMLD6Gjk',
        is_live: null,
        air_at: '',
        created_at: '2016-09-26 21:25:45',
    },
    {
        id: 248,
        title: 'Kenny Voets v Steven Coene',
        description: '2015 9-ball',
        duration: '4692',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://www.youtube.com/embed/QEI6JT0iN1k',
        is_live: null,
        air_at: '',
        created_at: '2016-07-17 20:59:42',
    },
    {
        id: 1097,
        title: 'Jacob Watson vs Brian Parks',
        description: '2016 8-ball / 9-ball',
        duration: '3178',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://youtube.com/embed/NoSh_rwu2Qw',
        is_live: null,
        air_at: '',
        created_at: '2017-11-07 23:01:22',
    },
    {
        id: 3615,
        title: 'Reyes vs Corey Deuel',
        description: '2017 8-ball',
        duration: '4799',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/ihzCCmugmKU',
        is_live: null,
        air_at: '',
        created_at: '2019-01-11 19:48:24',
    },
    {
        id: 13234,
        title: 'Shane Van Boening vs Carlo Biado',
        description: '2019 8-ball',
        duration: '3952',
        video_meta: '',
        embed_url: 'https://www.youtube.com/embed/i3mbY19R4O8',
        is_live: null,
        air_at: '',
        created_at: '2019-11-03 00:01:10',
    },
    {
        id: 522,
        title: 'Tim Christopher vs Jonny Warren',
        description: '2016 8-ball',
        duration: '5869',
        video_meta: '{ "game_type": "8-ball" }',
        embed_url: 'https://youtube.com/embed/Ynkqx3WkrQg',
        is_live: null,
        air_at: '',
        created_at: '2016-11-07 17:36:35',
    },
    {
        id: 790,
        title: 'Billy Thorpe vs Francisco Bustamante',
        description: '2017 9-ball',
        duration: '4690',
        video_meta: '{ "game_type": "9-ball" }',
        embed_url: 'https://youtube.com/embed/dyatSxzNchc',
        is_live: null,
        air_at: '',
        created_at: '2017-02-02 21:29:46',
    },
    {
        id: 739,
        title: 'Mika Immonen vs Fedor Gorst',
        description: '2016 Derby City Classic One Pocket',
        duration: '2778',
        video_meta: '{ "game_type": "1-pocket" }',
        embed_url: 'https://youtube.com/embed/MjrBSjfuwps',
        is_live: null,
        air_at: '',
        created_at: '2017-01-26 17:17:20',
    },
]);

/**
  ┌────────────────────────────────────────────────────────────────────────────┐
  │                                                                            │
  │ Local tests                                                                │
  │                                                                            │
  └────────────────────────────────────────────────────────────────────────────┘
*/

describe('Schedule - Local', () => {
    it('should have a duration equaling 4643', () => {
        const model: ModelSchedule = collection.at(0);

        expect(model.getDuration()).to.equal(4643);
    });

    it('should have a title', () => {
        const model: ModelSchedule = collection.at(0);

        expect(model.getTitle()).to.equal('Billy Thorpe vs Jason Klatt');
    });

    it('should have ', () => {
        const model: ModelSchedule = collection.getCurrentVideo();
        const time: number = collection.getTimeForCurrentVideo();

        console.log('playing', model.getTitle(), 'at', time);
        // expect(model.getTitle()).to.equal('Dimitris Loukatos vs Nick Ekonomopoulos');
    });
});
